import { google } from "googleapis";
import { validateWastageRows, rowKey, type WastageExportRow } from "./pure.js";
import { getGoogleSheetsAuth } from "./google-auth.js";
const columns = ["Store", "Date", "Food Type", "Quantity"] as const;
type SheetsClient = { spreadsheets: { values: { get(args: { spreadsheetId: string; range: string }): Promise<{ data: { values?: unknown[][] } }>; batchUpdate(args: { spreadsheetId: string; requestBody: { valueInputOption: string; data: Array<{ range: string; values: unknown[][] }> } }): Promise<unknown> } } };
type GoogleSheetsApiError = { response?: { status?: number; statusText?: string; data?: unknown } };
export function safeGoogleSheetsErrorDetails(error: unknown) {
  const response = (error as GoogleSheetsApiError)?.response;
  const data = response?.data as { error?: { message?: unknown }; error_description?: unknown } | undefined;
  const candidates = [data?.error?.message, data?.error_description, response?.statusText, error instanceof Error ? error.message : undefined];
  const rawMessage = candidates.find((value): value is string => typeof value === "string" && value.trim().length > 0) ?? "Google Sheets request rejected";
  const message = rawMessage.replace(/-----BEGIN [^-]+-----[\s\S]*?-----END [^-]+-----/g, "[redacted]").replace(/Bearer\s+\S+/gi, "Bearer [redacted]").replace(/(authorization|private[_ -]?key|password|secret|token)\s*[:=]\s*\S+/gi, "$1=[redacted]").slice(0, 240);
  return { status: response?.status, message };
}
export function readGoogleSheetsConfig() { const value = { spreadsheetId: process.env.GOOGLE_SHEETS_SPREADSHEET_ID?.trim(), tabName: process.env.GOOGLE_SHEETS_TAB_NAME?.trim() }; const missing = Object.entries(value).filter(([, item]) => !item).map(([name]) => name); if (missing.length) throw new Error(`Google Sheets configuration is missing: ${missing.join(", ")}`); return value as { spreadsheetId: string; tabName: string }; };
export function validateSheetRows(values: unknown[][] | undefined) { if (!values?.length) return { hasHeader: false, rows: [] as Array<{ rowNumber: number; row: WastageExportRow }> }; const header = values[0] ?? []; if (header.length !== 4 || columns.some((column, i) => header[i] !== column)) throw new Error("Google Sheet has unexpected wastage headers"); const rows: Array<{ rowNumber: number; row: WastageExportRow }> = []; for (let i = 1; i < values.length; i++) { const value = values[i] ?? []; if (!value.length || value.every(item => String(item ?? "").trim() === "")) continue; const row = { Store: String(value[0] ?? ""), Date: String(value[1] ?? ""), "Food Type": String(value[2] ?? ""), Quantity: Number(value[3]) }; if (!row.Store.trim() || !row.Date.trim() || !row["Food Type"].trim() || !Number.isFinite(row.Quantity)) throw new Error(`Google Sheet row ${i + 1} is invalid`); rows.push({ rowNumber: i + 1, row }); } return { hasHeader: true, rows }; }
export async function syncWastageRowsWithClient(sheets: SheetsClient, spreadsheetId: string, tabName: string, rows: WastageExportRow[]) { validateWastageRows(rows); const range = `'${tabName.replace(/'/g, "''")}'!A:D`; const response = await sheets.spreadsheets.values.get({ spreadsheetId, range }); const values = response.data.values ?? undefined; const existing = validateSheetRows(values); const byKey = new Map<string, { rowNumber: number; row: WastageExportRow }>(); for (const item of existing.rows) { const itemKey = rowKey(item.row); if (byKey.has(itemKey)) throw new Error(`Google Sheet contains duplicate wastage row: ${itemKey}`); byKey.set(itemKey, item); } const data: Array<{ range: string; values: unknown[][] }> = []; if (!existing.hasHeader) data.push({ range: `'${tabName.replace(/'/g, "''")}'!A1:D1`, values: [columns as unknown as string[]] }); const appended: WastageExportRow[] = []; let updated = 0; for (const row of rows) { const current = byKey.get(rowKey(row)); if (!current) appended.push(row); else if (current.row.Quantity !== row.Quantity) { data.push({ range: `'${tabName.replace(/'/g, "''")}'!D${current.rowNumber}`, values: [[row.Quantity]] }); updated++; } } if (appended.length) { const start = (values?.length ?? 1) + 1; data.push({ range: `'${tabName.replace(/'/g, "''")}'!A${start}:D${start + appended.length - 1}`, values: appended.map(row => [row.Store, row.Date, row["Food Type"], row.Quantity]) }); } if (data.length) await sheets.spreadsheets.values.batchUpdate({ spreadsheetId, requestBody: { valueInputOption: "RAW", data } }); return { updated, appended: appended.length, unchanged: rows.length - updated - appended.length }; }
export async function syncWastageRows(rows: WastageExportRow[]) { const cfg = readGoogleSheetsConfig(); const auth = await getGoogleSheetsAuth(); const sheets = google.sheets({ version: "v4", auth }); try { return await syncWastageRowsWithClient(sheets as unknown as SheetsClient, cfg.spreadsheetId, cfg.tabName, rows); } catch (error) { const details = safeGoogleSheetsErrorDetails(error); if (details.status === 401 || details.status === 403) throw new Error(`Google Sheets permission denied (HTTP ${details.status}): ${details.message}`); throw error; } }
