import { getAuthUserId } from "@convex-dev/auth/server";
import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { requireLocationAccess, requireLocationManager } from "./permissions";

const frequencyValidator = v.union(v.literal("weekly"), v.literal("monthly"), v.literal("every_x_weeks"), v.literal("every_x_months"), v.literal("annual"), v.literal("one_off"));
const fieldValidator = v.object({ key: v.string(), label: v.string(), type: v.union(v.literal("temperature"), v.literal("number"), v.literal("yes_no"), v.literal("completed"), v.literal("date"), v.literal("text"), v.literal("actions"), v.literal("pdf")), minimum: v.optional(v.number()), maximum: v.optional(v.number()) });
const answerValidator = v.object({ key: v.string(), value: v.string() });

async function signedIn(ctx: any) { const userId = await getAuthUserId(ctx); if (!userId) throw new Error("You must be signed in"); return userId; }
function nextDue(frequency: string, interval = 1, from: number) { const date = new Date(from); if (frequency === "one_off") return from; if (frequency === "weekly") date.setDate(date.getDate() + 7); if (frequency === "monthly") date.setMonth(date.getMonth() + 1); if (frequency === "every_x_weeks") date.setDate(date.getDate() + 7 * Math.max(1, interval)); if (frequency === "every_x_months") date.setMonth(date.getMonth() + Math.max(1, interval)); if (frequency === "annual") date.setFullYear(date.getFullYear() + 1); return date.getTime(); }

export const dashboard = query({ args: { locationId: v.id("locations") }, handler: async (ctx, args) => { await requireLocationAccess(ctx, args.locationId); const now = Date.now(); const startOfToday = new Date(); startOfToday.setHours(0, 0, 0, 0); const all = (await ctx.db.query("additionalRequirements").withIndex("by_location", q => q.eq("locationId", args.locationId)).collect()).filter(item => item.active).sort((a, b) => a.order - b.order); const allCompletions = await Promise.all((await ctx.db.query("additionalCompletions").withIndex("by_location", q => q.eq("locationId", args.locationId)).collect()).map(async item => ({ ...item, teamMemberName: (await ctx.db.get(item.teamMemberId))?.name, documentUrl: item.documentStorageId ? await ctx.storage.getUrl(item.documentStorageId) : null }))); const requirements = all.filter(item => item.nextDueAt <= now || allCompletions.some(completion => completion.requirementId === item._id && completion.completedAt >= startOfToday.getTime())); return { requirements, completions: allCompletions }; } });
export const history = query({ args: { locationId: v.id("locations"), start: v.number(), end: v.number() }, handler: async (ctx, args) => { await requireLocationAccess(ctx, args.locationId); return await Promise.all((await ctx.db.query("additionalCompletions").withIndex("by_location", q => q.eq("locationId", args.locationId)).collect()).filter(item => item.completedAt >= args.start && item.completedAt <= args.end).map(async item => ({ ...item, teamMemberName: (await ctx.db.get(item.teamMemberId))?.name, requirementTitle: (await ctx.db.get(item.requirementId))?.title, documentUrl: item.documentStorageId ? await ctx.storage.getUrl(item.documentStorageId) : null }))); } });
export const list = query({ args: { locationId: v.id("locations") }, handler: async (ctx, args) => { await requireLocationManager(ctx, args.locationId); return (await ctx.db.query("additionalRequirements").withIndex("by_location", q => q.eq("locationId", args.locationId)).collect()).filter(item => item.active).sort((a, b) => a.order - b.order); } });
export const generateUploadUrl = mutation({ args: {}, handler: async (ctx) => { await signedIn(ctx); return await ctx.storage.generateUploadUrl(); } });
export const add = mutation({ args: { locationId: v.id("locations"), title: v.string(), description: v.optional(v.string()), frequency: frequencyValidator, interval: v.optional(v.number()), nextDueAt: v.number(), fields: v.array(fieldValidator) }, handler: async (ctx, args) => { await requireLocationManager(ctx, args.locationId); const all = await ctx.db.query("additionalRequirements").withIndex("by_location", q => q.eq("locationId", args.locationId)).collect(); return await ctx.db.insert("additionalRequirements", { ...args, title: args.title.trim(), active: true, order: all.length }); } });
export const update = mutation({ args: { requirementId: v.id("additionalRequirements"), title: v.string(), description: v.optional(v.string()), frequency: frequencyValidator, interval: v.optional(v.number()), nextDueAt: v.number(), fields: v.array(fieldValidator) }, handler: async (ctx, args) => { const requirement = await ctx.db.get(args.requirementId); if (!requirement) throw new Error("Requirement not found"); if (requirement.active !== true) throw new Error("This configuration version is no longer active"); await requireLocationManager(ctx, requirement.locationId); const root = requirement.versionRootId ?? requirement._id; const now = Date.now(); await ctx.db.patch(args.requirementId, { active: false, deactivatedAt: now }); await ctx.db.insert("additionalRequirements", { locationId: requirement.locationId, title: args.title.trim(), description: args.description, frequency: args.frequency, interval: args.interval, nextDueAt: args.nextDueAt, fields: args.fields, active: true, order: requirement.order, versionRootId: root }); } });
export const remove = mutation({ args: { requirementId: v.id("additionalRequirements") }, handler: async (ctx, args) => { const requirement = await ctx.db.get(args.requirementId); if (!requirement) throw new Error("Requirement not found"); await requireLocationManager(ctx, requirement.locationId); await ctx.db.patch(args.requirementId, { active: false, deactivatedAt: Date.now() }); } });
export const reorder = mutation({ args: { requirementId: v.id("additionalRequirements"), direction: v.union(v.literal("up"), v.literal("down")) }, handler: async (ctx, args) => { const current = await ctx.db.get(args.requirementId); if (!current) throw new Error("Requirement not found"); await requireLocationManager(ctx, current.locationId); const items = (await ctx.db.query("additionalRequirements").withIndex("by_location", q => q.eq("locationId", current.locationId)).collect()).filter(item => item.active).sort((a, b) => a.order - b.order); const index = items.findIndex(item => item._id === args.requirementId); const target = args.direction === "up" ? index - 1 : index + 1; if (index < 0 || !items[target]) return; await ctx.db.patch(items[index]._id, { order: items[target].order }); await ctx.db.patch(items[target]._id, { order: items[index].order }); } });
export const complete = mutation({ args: { locationId: v.id("locations"), requirementId: v.id("additionalRequirements"), teamMemberId: v.id("teamMembers"), answers: v.array(answerValidator), checkedDate: v.optional(v.string()), nextDueAt: v.optional(v.number()), certificateReference: v.optional(v.string()), documentStorageId: v.optional(v.id("_storage")), documentName: v.optional(v.string()) }, handler: async (ctx, args) => { const userId = await signedIn(ctx); await requireLocationAccess(ctx, args.locationId); const requirement = await ctx.db.get(args.requirementId); if (!requirement || requirement.locationId !== args.locationId) throw new Error("Requirement does not belong to this location"); if (requirement.active !== true) throw new Error("This configuration version is no longer active"); const teamMember = await ctx.db.get(args.teamMemberId); if (!teamMember || teamMember.locationId !== args.locationId) throw new Error("Team member does not belong to this location"); const now = Date.now(); const scheduledDueAt = requirement.nextDueAt; const due = args.nextDueAt ?? nextDue(requirement.frequency, requirement.interval, now); const id = await ctx.db.insert("additionalCompletions", { ...args, scheduledDueAt, completedAt: now, nextDueAt: due, completedBy: userId }); if (requirement.frequency === "one_off") await ctx.db.patch(requirement._id, { active: false, deactivatedAt: Date.now() }); else await ctx.db.patch(requirement._id, { nextDueAt: due }); return id; } });