import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { Infer, v } from "convex/values";

export const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  STAFF: "staff",
} as const;

export const roleValidator = v.union(
  v.literal(ROLES.ADMIN),
  v.literal(ROLES.MANAGER),
  v.literal(ROLES.STAFF),
);
export type Role = Infer<typeof roleValidator>;

const schema = defineSchema({
  ...authTables,
  users: defineTable({
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    role: v.optional(roleValidator),
  }).index("email", ["email"]),
  organisations: defineTable({ name: v.string(), timezone: v.string() }),
  locations: defineTable({
    organisationId: v.id("organisations"),
    name: v.string(),
    shortName: v.string(),
    timezone: v.string(),
    active: v.boolean(),
  }).index("by_organisation", ["organisationId"]),
  memberships: defineTable({
    userId: v.id("users"),
    locationId: v.id("locations"),
    role: roleValidator,
  }).index("by_user", ["userId"]),
  teamMembers: defineTable({
    locationId: v.id("locations"),
    name: v.string(),
    active: v.boolean(),
    createdAt: v.number(),
  }).index("by_location", ["locationId"]),
  equipment: defineTable({
    locationId: v.id("locations"),
    name: v.string(),
    type: v.string(),
    preferredTemperature: v.optional(v.number()),
    maximumTemperature: v.optional(v.number()),
    order: v.number(),
    active: v.boolean(),
  }).index("by_location", ["locationId"]),
  scheduledTasks: defineTable({
    locationId: v.id("locations"),
    title: v.string(),
    kind: v.union(v.literal("temperature"), v.literal("probe")),
    session: v.optional(v.union(v.literal("AM"), v.literal("PM"))),
    dueLabel: v.string(),
    status: v.union(v.literal("complete"), v.literal("due"), v.literal("upcoming"), v.literal("overdue")),
    completedAt: v.optional(v.number()),
    completedBy: v.optional(v.id("users")),
  }).index("by_location", ["locationId"]),
  temperatureRounds: defineTable({
    locationId: v.id("locations"),
    session: v.union(v.literal("AM"), v.literal("PM")),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location", ["locationId"]),
  temperatureReadings: defineTable({
    roundId: v.id("temperatureRounds"),
    equipmentId: v.id("equipment"),
    locationId: v.id("locations"),
    temperature: v.number(),
    result: v.union(v.literal("normal"), v.literal("within_limit"), v.literal("fail")),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
    voided: v.boolean(),
  }).index("by_round", ["roundId"]).index("by_location", ["locationId"]),
  probeProducts: defineTable({
    organisationId: v.id("organisations"),
    name: v.string(),
    minimumTemperature: v.number(),
    holdMinutes: v.number(),
    locationIds: v.array(v.id("locations")),
    order: v.optional(v.number()),
    active: v.boolean(),
  }).index("by_organisation", ["organisationId"]),
  checklistQuestions: defineTable({
    locationId: v.id("locations"),
    checklist: v.union(v.literal("opening"), v.literal("closing")),
    question: v.string(),
    order: v.number(),
    active: v.boolean(),
  }).index("by_location_checklist", ["locationId", "checklist"]),
  checklistResponses: defineTable({
    locationId: v.id("locations"),
    checklist: v.union(v.literal("opening"), v.literal("closing")),
    questionId: v.id("checklistQuestions"),
    answer: v.union(v.literal("yes"), v.literal("no"), v.literal("na")),
    problem: v.optional(v.string()),
    action: v.optional(v.string()),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location_checklist", ["locationId", "checklist"]),
  checklistSignOffs: defineTable({
    locationId: v.id("locations"),
    checklist: v.union(v.literal("opening"), v.literal("closing")),
    dateKey: v.string(),
    completedAt: v.number(),
    completedBy: v.id("users"),
    teamMemberId: v.id("teamMembers"),
  }).index("by_location_checklist_date", ["locationId", "checklist", "dateKey"]),
  securitySignOffs: defineTable({
    locationId: v.id("locations"),
    session: v.union(v.literal("AM"), v.literal("PM")),
    dateKey: v.string(),
    completedAt: v.number(),
    completedBy: v.id("users"),
    teamMemberId: v.id("teamMembers"),
  }).index("by_location_session_date", ["locationId", "session", "dateKey"]),
  securityQuestions: defineTable({
    locationId: v.id("locations"),
    session: v.union(v.literal("AM"), v.literal("PM")),
    question: v.string(),
    order: v.number(),
    active: v.boolean(),
  }).index("by_location_session", ["locationId", "session"]),
  securityResponses: defineTable({
    locationId: v.id("locations"),
    session: v.union(v.literal("AM"), v.literal("PM")),
    questionId: v.id("securityQuestions"),
    answer: v.literal("yes"),
    issue: v.optional(v.string()),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location_session", ["locationId", "session"]),
  foodChecks: defineTable({
    locationId: v.id("locations"),
    product: v.string(),
    quantity: v.optional(v.string()),
    temperature: v.number(),
    result: v.union(v.literal("pass"), v.literal("fail")),
    action: v.optional(v.string()),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location", ["locationId"]),
  wastageItems: defineTable({
    locationId: v.id("locations"),
    name: v.string(),
    active: v.boolean(),
    order: v.number(),
  }).index("by_location", ["locationId"]),
  wastageRecords: defineTable({
    locationId: v.id("locations"),
    itemId: v.optional(v.id("wastageItems")),
    itemName: v.optional(v.string()),
    quantity: v.optional(v.string()),
    notes: v.optional(v.string()),
    noWaste: v.boolean(),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location", ["locationId"]),
  cleaningTasks: defineTable({
    locationId: v.id("locations"),
    name: v.string(),
    frequency: v.union(v.literal("after_use"), v.literal("daily"), v.literal("weekly"), v.literal("specific_days")),
    weekdays: v.array(v.number()),
    active: v.boolean(),
    order: v.number(),
  }).index("by_location", ["locationId"]),
  cleaningCompletions: defineTable({
    locationId: v.id("locations"),
    taskId: v.id("cleaningTasks"),
    dateKey: v.string(),
    completedAt: v.number(),
    completedBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_location_date", ["locationId", "dateKey"]).index("by_task", ["taskId"]),
  trainingRequirements: defineTable({
    locationId: v.id("locations"),
    title: v.string(),
    active: v.boolean(),
    order: v.number(),
  }).index("by_location", ["locationId"]),
  trainingCompletions: defineTable({
    locationId: v.id("locations"),
    requirementId: v.id("trainingRequirements"),
    teamMemberId: v.id("teamMembers"),
    completedAt: v.number(),
    completedBy: v.id("users"),
  }).index("by_location", ["locationId"]).index("by_requirement", ["requirementId"]).index("by_member", ["teamMemberId"]),
  rechecks: defineTable({
    locationId: v.id("locations"),
    issueId: v.id("issues"),
    readingId: v.optional(v.id("temperatureReadings")),
    temperature: v.number(),
    result: v.union(v.literal("pass"), v.literal("fail")),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_issue", ["issueId"]),
  issues: defineTable({
    locationId: v.id("locations"),
    category: v.string(),
    title: v.string(),
    description: v.string(),
    status: v.union(v.literal("open"), v.literal("monitoring"), v.literal("resolved")),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
    action: v.optional(v.string()),
    resolvedAt: v.optional(v.number()),
    resolvedBy: v.optional(v.id("users")),
    resolutionNote: v.optional(v.string()),
    originalReading: v.optional(v.string()),
  }).index("by_location", ["locationId"]),
  issueUpdates: defineTable({
    issueId: v.id("issues"),
    locationId: v.id("locations"),
    updateType: v.union(v.literal("immediate_action"), v.literal("further_action"), v.literal("resolution"), v.literal("status_change")),
    note: v.string(),
    status: v.union(v.literal("open"), v.literal("monitoring"), v.literal("resolved")),
    createdAt: v.number(),
    createdBy: v.id("users"),
    teamMemberId: v.optional(v.id("teamMembers")),
  }).index("by_issue", ["issueId"]).index("by_location", ["locationId"]),
  auditEvents: defineTable({
    locationId: v.optional(v.id("locations")),
    userId: v.id("users"),
    type: v.string(),
    detail: v.string(),
    createdAt: v.number(),
  }).index("by_location", ["locationId"]),
});

export default schema;
