import { Button } from "@/components/ui/button";
import { Check, ChevronLeft } from "lucide-react";
import { useState } from "react";

type CleaningTask = { _id: string; name: string; frequency?: string };
type CleaningCompletion = { taskId: string; completedAt?: number | string; teamMemberName?: string | null };
type TeamMember = { _id: string; name: string };
type Props = { locationName: string; tasks: CleaningTask[]; completions: CleaningCompletion[]; teamMembers: TeamMember[]; onComplete: (taskId: string, teamMemberId: string) => Promise<void>; onBack: () => void };

const timeLabel = (value?: number | string) => value === undefined ? "" : new Date(value).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });

export default function InlineCleaning({ locationName, tasks, completions, teamMembers, onComplete, onBack }: Props) {
  const [selected, setSelected] = useState<Record<string, string>>({});
  return <div className="min-h-screen bg-[#f6f7f5] text-[#171918]"><header className="border-b border-black/[0.07] bg-white"><div className="mx-auto flex max-w-2xl items-center gap-3 px-5 py-4"><Button variant="ghost" size="icon" onClick={onBack}><ChevronLeft /></Button><div><p className="font-semibold">Cleaning</p><p className="text-xs text-[#89918b]">{locationName} · Today</p></div></div></header><main className="mx-auto max-w-2xl px-4 py-8 sm:px-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#89918b]">Daily checks</p><h1 className="mt-2 text-3xl font-semibold">Cleaning jobs</h1><p className="mt-2 text-sm text-[#727a74]">Complete each cleaning job with the person who carried it out.</p><div className="mt-7 space-y-2">{tasks.map((task) => { const completion = completions.find((item) => item.taskId === task._id); const frequencyLabel = task.frequency === "after_use" ? "After use" : task.frequency === "specific_days" ? "Scheduled day" : task.frequency ? task.frequency[0].toUpperCase() + task.frequency.slice(1) : "Scheduled"; return <div key={task._id} className="rounded-2xl border border-black/[0.07] bg-white p-5"><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{task.name}</p><p className="mt-1 text-xs text-[#89918b]">{frequencyLabel}</p></div>{completion ? <span className="text-right text-sm font-semibold text-[#2d7951]"><span className="flex items-center justify-end gap-1">Completed <Check className="size-4" /></span><span className="mt-1 block text-xs font-normal">{completion.teamMemberName ?? "Not recorded"} · {timeLabel(completion.completedAt)}</span></span> : <Button disabled={!selected[task._id]} className="bg-[#ffde56] font-semibold text-[#171717]" onClick={() => onComplete(task._id, selected[task._id])}>Complete <Check className="ml-1 size-4" /></Button>}</div>{!completion && <label className="mt-4 block text-sm font-semibold">Completed by<select value={selected[task._id] ?? ""} onChange={(event) => setSelected((current) => ({ ...current, [task._id]: event.target.value }))} className="mt-2 h-11 w-full rounded-xl border border-black/[0.1] bg-white px-3"><option value="">Select team member</option>{teamMembers.map((member) => <option key={member._id} value={member._id}>{member.name}</option>)}</select></label>}</div>; })}{!tasks.length && <div className="rounded-2xl border border-black/[0.07] bg-white p-5 text-sm text-[#727a74]">No cleaning jobs are due today.</div>}</div></main></div>;
}
