import { Button } from "@/components/ui/button";
import { ArrowLeft, CheckCircle2 } from "lucide-react";

const dateLabel = (value: Date) => new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(value);
const timeLabel = (value?: number) => value ? new Date(value).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }) : "—";

export default function MobileDayView({ location, date, archive, additionalHistory = [], equipment, onBack }: any) {
  const rounds = archive?.rounds ?? [];
  const readings = archive?.readings ?? [];
  const readingFor = (session: string, equipmentId: any) => {
    const roundIds = rounds.filter((round: any) => round.session === session).map((round: any) => round._id);
    return readings.find((reading: any) => roundIds.includes(reading.roundId) && reading.equipmentId === equipmentId);
  };
  const checklistResponses = [...(archive?.questions?.opening ?? []), ...(archive?.questions?.closing ?? [])];
  const securityResponses = [...(archive?.securityResponses?.AM ?? []), ...(archive?.securityResponses?.PM ?? [])];

  return <div className="min-h-screen bg-[#f6f7f5]">
    <header className="border-b border-black/[0.07] bg-white"><div className="mx-auto flex max-w-2xl items-center gap-3 px-4 py-4"><Button variant="ghost" size="icon" onClick={onBack}><ArrowLeft className="size-5" /></Button><div><p className="font-semibold">Daily inspection record</p><p className="text-xs text-[#89918b]">{location?.name}</p></div></div></header>
    <main className="mx-auto max-w-2xl px-4 py-7 sm:px-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#89918b]">Day inspection</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">{dateLabel(date)}</h1>
      <div className="mt-7 space-y-4">
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Fridge temperatures</h2><div className="mt-4 space-y-2">{equipment.map((item: any, index: number) => { const am = readingFor("AM", item._id); const pm = readingFor("PM", item._id); return <div key={item._id} className="rounded-xl bg-[#fafbf9] p-4"><p className="font-semibold">Fridge {index + 1}</p><div className="mt-2 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-[#89918b]">AM</p><p className={am?.result === "fail" ? "font-semibold text-[#b64738]" : "font-semibold"}>{am ? `${am.temperature}°C` : "—"}</p></div><div><p className="text-xs text-[#89918b]">PM</p><p className={pm?.result === "fail" ? "font-semibold text-[#b64738]" : "font-semibold"}>{pm ? `${pm.temperature}°C` : "—"}</p></div></div></div>; })}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Food probes</h2><div className="mt-4 space-y-2">{(archive?.probes ?? []).length ? archive.probes.map((probe: any) => <div key={probe._id} className="flex items-center justify-between gap-3 rounded-xl bg-[#fafbf9] p-4 text-sm"><div><p className="font-semibold">{probe.product}</p><p className="mt-1 text-xs text-[#89918b]">{probe.quantity ?? "Quantity not recorded"} · {probe.teamMemberName ?? "Team member"}</p></div><span className={probe.result === "pass" ? "font-semibold text-[#2d7951]" : "font-semibold text-[#b64738]"}>{probe.temperature}°C · {timeLabel(probe.createdAt)}</span></div>) : <p className="text-sm text-[#89918b]">No probe records for this day.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Security</h2><div className="mt-4 space-y-2">{securityResponses.length ? securityResponses.map((response: any) => <div key={response._id} className="rounded-xl bg-[#fafbf9] p-4 text-sm"><p className="font-semibold">{response.session} · Complete</p><p className="mt-1 text-[#727a74]">{response.issue ?? "No issues reported"} · {timeLabel(response.createdAt)}</p></div>) : <p className="text-sm text-[#89918b]">No security records for this day.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Cleaning</h2><div className="mt-4 space-y-2">{(archive?.cleaningCompletions ?? []).length ? archive.cleaningCompletions.map((completion: any) => <div key={completion._id} className="flex items-center justify-between gap-3 rounded-xl bg-[#fafbf9] p-4 text-sm"><span className="font-semibold">{archive.cleaningTasks?.find((task: any) => task._id === completion.taskId)?.name ?? "Cleaning task"}</span><span className="text-right text-[#2d7951]">{completion.teamMemberName ?? "Team member"}<br />{timeLabel(completion.completedAt)}</span></div>) : <p className="text-sm text-[#89918b]">No cleaning records for this day.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Wastage</h2><div className="mt-4 space-y-2">{(archive?.wastageRecords ?? []).length ? archive.wastageRecords.map((record: any) => <div key={record._id} className="flex items-center justify-between gap-3 rounded-xl bg-[#fafbf9] p-4 text-sm"><span className="font-semibold">{record.noWaste ? "No Waste" : record.itemName}</span><span className="text-right">{record.quantity ?? "—"}<br /><span className="text-xs text-[#89918b]">{record.teamMemberName ?? "Team member"}</span></span></div>) : <p className="text-sm text-[#89918b]">No wastage records for this day.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Additional checks</h2><div className="mt-4 space-y-2">{additionalHistory.length ? additionalHistory.map((item: any) => <div key={item._id} className="rounded-xl bg-[#fafbf9] p-4 text-sm"><p className="font-semibold">{item.requirementTitle}</p><p className="mt-1 text-[#727a74]">Completed by {item.teamMemberName ?? "Team member"} · {timeLabel(item.completedAt)}</p>{item.documentUrl && <a href={item.documentUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block font-semibold text-[#27814f]">View certificate</a>}</div>) : <p className="text-sm text-[#89918b]">No additional checks recorded for this day.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Corrective actions</h2><div className="mt-4 space-y-2">{(archive?.issues ?? []).length ? archive.issues.map((issue: any) => <div key={issue._id} className="rounded-xl bg-[#fff8f6] p-4 text-sm"><p className="font-semibold">{issue.title}</p><p className="mt-1 text-[#727a74]">{issue.description}</p><p className="mt-2 text-[#8f3a31]">{issue.action ?? "Action not yet recorded"}</p></div>) : <p className="flex items-center gap-2 text-sm text-[#2d7951]"><CheckCircle2 className="size-4" /> No corrective actions recorded.</p>}</div></section>
        <section className="rounded-2xl border border-black/[0.07] bg-white p-5"><h2 className="text-lg font-semibold">Checklist Tasks</h2><div className="mt-4 space-y-2">{checklistResponses.length ? checklistResponses.map((response: any) => <div key={response._id} className="rounded-xl bg-[#fafbf9] p-4 text-sm"><p className="font-semibold">{response.question ?? "Checklist task"}</p><p className={response.answer === "no" ? "mt-1 font-semibold text-[#b64738]" : "mt-1 font-semibold text-[#2d7951]"}>{response.answer === "no" ? "Issue identified" : response.answer === "na" ? "Not applicable" : "Completed"}</p><p className="mt-1 text-[#727a74]">Completed by {response.teamMemberName ?? "Team member"} · {timeLabel(response.createdAt)}</p>{response.action && <div className="mt-3 border-t border-black/[0.07] pt-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#89918b]">Action taken</p><p className="mt-1 text-[#727a74]">{response.action}</p></div>}</div>) : <p className="text-sm text-[#89918b]">No checklist task records for this day.</p>}</div></section>
      </div>
    </main>
  </div>;
}
